window.CHARACTERS = [
  { id: 'cocoa', name: 'COCOA', season: 'SEASON 02', period: '26.08', published: '2026-08-26', images: ['images/cocoa/top.jpg'], detailImages: ['images/cocoa/1.jpg', 'images/cocoa/2.jpg', 'images/cocoa/3.jpg'], voteImage: 'images/cocoa/r.jpg', performance: { tiktok: 0, instagram: 0, chili: 8969 }, creatorRating: 4, creatorNote: '夜の夏祭りで素敵な浴衣姿で魅了' },
  { id: 'keiko', name: 'KEIKO', season: 'SEASON 02', period: '26.08', published: '2026-08-22', images: ['images/keiko/top.jpg'], detailImages: ['images/keiko/1.jpg', 'images/keiko/2.jpg', 'images/keiko/3.jpg'], voteImage: 'images/keiko/r.jpg', performance: { tiktok: 0, instagram: 0, chili: 3252 }, creatorRating: 4, creatorNote: '更衣室、ビジネスホテルでこっそり撮影' },
  { id: 'kei', name: 'KEI', season: 'SEASON 02', period: '26.08', published: '2026-08-15', images: ['images/kei/top.jpg'], detailImages: ['images/kei/1.jpg', 'images/kei/2.jpg', 'images/kei/3.jpg'], voteImage: 'images/kei/r.jpg', performance: { tiktok: 13701, instagram: 6052, chili: 24988 }, creatorRating: 5, creatorNote: '第2世代エース。全SNSのPVに貢献' },
  { id: 'kumi', name: 'KUMI', season: 'SEASON 02', period: '26.08', published: '2026-08-08', images: ['images/kumi/top.jpg'], detailImages: ['images/kumi/1.jpg', 'images/kumi/2.jpg', 'images/kumi/3.jpg'], voteImage: 'images/kumi/r.jpg', performance: { tiktok: 1531, instagram: 0, chili: 19997 }, creatorRating: 5, creatorNote: '可愛エロヤンキー。甘めの雰囲気も得意。' },
  { id: 'karina', name: 'KARINA', season: 'SEASON 02', period: '26.08', published: '2026-08-01', images: ['images/karina/top.jpg'], detailImages: ['images/karina/1.jpg', 'images/karina/2.jpg', 'images/karina/3.jpg'], voteImage: 'images/karina/r.jpg', performance: { tiktok: 8321, instagram: 1338, chili: 23565 }, creatorRating: 5, creatorNote: '第1世代エース。可愛いギャル枠' },
  { id: 'aki', name: 'AKI', season: 'SEASON 01', period: '26.07', published: '2026-07-12', images: ['images/aki/top.jpg'], detailImages: ['images/aki/1.jpg', 'images/aki/2.jpg', 'images/aki/3.jpg'], voteImage: 'images/aki/r.jpg', performance: { tiktok: 0, instagram: 0, chili: 36038 }, creatorRating: 4, creatorNote: 'Chiliで1本で25,000PV over' },
  { id: 'iroha', name: 'IROHA', season: 'SEASON 01', period: '26.07', published: '2026-07-26', images: ['images/iroha/top.jpg'], detailImages: ['images/iroha/1.jpg', 'images/iroha/2.jpg', 'images/iroha/3.jpg'], voteImage: 'images/iroha/r.jpg', performance: { tiktok: 3115, instagram: 892, chili: 14596 }, creatorRating: 3, creatorNote: 'コンセプトを固めすぎて自由度が低かった。' },
  { id: 'emi', name: 'EMI', season: 'SEASON 01', period: '26.07', published: '2026-07-19', images: ['images/emi/top.jpg'], detailImages: ['images/emi/1.jpg', 'images/emi/2.jpg', 'images/emi/3.jpg'], voteImage: 'images/emi/r.jpg', performance: { tiktok: 1799, instagram: 250, chili: 4474 }, creatorRating: 2, creatorNote: '歯科衛生士設定で不自由な事が多かった。' },
  { id: 'ai', name: 'AI', season: 'SEASON 01', period: '26.07', published: '2026-07-05', images: ['images/ai/top.jpg'], detailImages: ['images/ai/1.jpg', 'images/ai/2.jpg', 'images/ai/3.jpg'], voteImage: 'images/ai/r.jpg', performance: { tiktok: 3505, instagram: 332, chili: 7315 }, creatorRating: 3, creatorNote: 'シュシュが可愛いが逆に使いにくくなった。' }
];
